"""Assembles a full raw-NHAMCS-schema single-row DataFrame from a curated
`PatientRecordRequest`, so it can be handed to
`ML.pipeline.preprocessing_pipeline.PreprocessingPipeline.transform()`
unmodified.

Fields the client omits are left null in every one of the ~900 raw
columns (`ML/saved_models/raw_schema.json`, generated by
`ML/scripts/generate_raw_schema.py`) rather than simply absent -- some
cleaning steps index a fixed, previously-learned column list without an
existence check, so a column missing entirely (not just null) raises a
KeyError. Leaving it null instead lets the pipeline's own fitted median /
"Missing"-category imputation fill it in exactly as it would for any
other missing value. Empirically verified end-to-end (Milestone 4): a
record with only the curated fields set produces all 866 expected model
features with zero NaNs.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import pandas as pd

from Backend.app.schemas.patient import PatientRecordRequest
from ML.ingestion.config import resolve_repo_path

RAW_SCHEMA_PATH = resolve_repo_path("ML/saved_models/raw_schema.json")

# API field -> (raw NHAMCS column, transform applied to the API value before insertion).
# TEMPF is stored with an implied decimal (raw 986 == 98.6 degrees F); every
# other mapped field is stored as-is in the raw dataset.
FIELD_MAPPING: dict[str, tuple[str, object]] = {
    "age": ("AGE", None),
    "sex": ("SEX", None),
    "race_ethnicity": ("RACERETH", None),
    "pulse": ("PULSE", None),
    "temperature_fahrenheit": ("TEMPF", lambda value: value * 10),
    "respiratory_rate": ("RESPR", None),
    "systolic_bp": ("BPSYS", None),
    "diastolic_bp": ("BPDIAS", None),
    "pulse_oximetry_percent": ("POPCT", None),
    "triage_level": ("IMMEDR", None),
    "arrived_by_ambulance": ("ARREMS", lambda value: 1 if value else 2),
    "wait_time_minutes": ("WAITTIME", None),
    "length_of_visit_minutes": ("LOV", None),
    "num_discharge_diagnoses": ("NUMDIS", None),
    "total_diagnoses": ("TOTDIAG", None),
    "consult_requested": ("CONSULT", lambda value: 1 if value else 0),
    "primary_diagnosis_code": ("DIAG1", None),
    "num_medications": ("NUMMED", None),
    "num_medications_given": ("NUMGIV", None),
}


@lru_cache
def _load_raw_columns(schema_path: Path = RAW_SCHEMA_PATH) -> tuple[str, ...]:
    payload = json.loads(schema_path.read_text(encoding="utf-8"))
    return tuple(payload["columns"])


class PatientRecordAssembler:
    """Stateless aside from the cached raw column list -- safe to
    instantiate once per process and reuse across requests."""

    def __init__(self) -> None:
        self._raw_columns = _load_raw_columns()

    def assemble(self, request: PatientRecordRequest) -> pd.DataFrame:
        row: dict[str, object] = dict.fromkeys(self._raw_columns)

        for api_field, value in request.model_dump(exclude_none=True).items():
            raw_column, transform = FIELD_MAPPING[api_field]
            row[raw_column] = transform(value) if transform else value

        return pd.DataFrame([row], columns=self._raw_columns)
